apiVersion: batch/v1
kind: Job
metadata:
  name: bq-indexer
spec:
  template:
    metadata:
      name: bq-indexer
    spec:
      containers:
      - name: bq-indexer
        image: gcr.io/MY_GOOGLE_CLOUD_PROJECT/bq-indexer
        # Uncomment to force repulling image. This is useful if you're modifying
        # indexer.py and want to test on GKE.
        # imagePullPolicy: Always
        volumeMounts:
        - name: dataset-config
          mountPath: /app/dataset_config
        command: ["python", "/app/indexer.py"]
        args: [
          "--elasticsearch_url", "http://LOAD_BALANCER_IP:9200/",
          "--dataset_config_dir", "/app/dataset_config"
        ]

      restartPolicy: Never

      volumes:
      - name: dataset-config
        configMap:
          name: dataset-config
