version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    ports:
      - 127.0.0.1:9200:9200
    environment:
      # Disable bootstrap checks so users don't have to fiddle with
      # vm.max_map_count. Note that this file is not used in production
      # deployments; bootstrap checks are still enabled for production
      # deployments.
      - "transport.host=localhost"
  indexer:
    build:
      # Context is project root, to pick up indexer_util and dataset_config
      context: ../
      dockerfile: bigquery/Dockerfile
    environment:
      # Needed to keep the samples file name unique across users.
      - USER
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      # For convenience, include 1000 Genomes by default.
      - DATASET_CONFIG_DIR=${DATASET_CONFIG_DIR:-dataset_config/1000_genomes}
    volumes:
      # Expose gcloud credentials. This is only needed for
      # local runs, which are authenticated as a user. This is not needed for
      # GKE runs, which are authenticated as service account. (The service
      # account credentials are automatically picked up.)
      - ~/.config/gcloud:/root/.config/gcloud
networks:
  default:
    external:
      # This is only needed for indexing data into an Elasticsearch container
      # from the data-explorer repo. Use the network from that repo.
      name: data-explorer_default
