version: '3'
services:
  indexer:
    build:
      context: .
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      # For convenience, include platinum_genomes by default.
      - DATASET_CONFIG_DIR=${DATASET_CONFIG_DIR:-dataset_config/platinum_genomes}
    volumes:
      # Expose gcloud credentials for pandas_gbq. This is only needed for
      # local runs, which are authenticated as a user. This is not needed for
      # GKE runs, which are authenticated as service account. (The service
      # account credentials are automatically picked up.)
      - ~/.config/gcloud:/root/.config/gcloud
networks:
  default:
    external:
      # Use network from data-explorer repo, so dataset will be indexed into
      # data-explorer's Elasticsearch container.
      name: dataexplorer_default
