version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    ports:
      - 127.0.0.1:9200:9200
  indexer:
    build:
      context: .
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - DATASET_CONFIG_DIR=${DATASET_CONFIG_DIR:-config/platinum_genomes}
    volumes:
      # Expose gcloud credentials for pandas_gbq. This is only needed for
      # local runs, which are authenticated as a user. This is not needed for
      # GKE runs, which are authenticated as service account. (The service
      # account credentials are automatically picked up.)
      - ~/.config/gcloud:/root/.config/gcloud
