version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    environment:
      # Disable the vm.max_map_counts bootstrap check, which is un-settable in
      # some instances (e.g. CircleCI)
      - "transport.host=localhost"
    ports:
      - 127.0.0.1:9200:9200
  indexer:
    build:
      # Context is project root, to pick up indexer_util and dataset_config
      context: ../
      dockerfile: bigquery/Dockerfile
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      # For convenience, include platinum_genomes by default.
      - DATASET_CONFIG_DIR=${DATASET_CONFIG_DIR:-dataset_config/platinum_genomes}
      - BILLING_PROJECT_ID=${BILLING_PROJECT_ID}
    volumes:
      # Expose gcloud credentials. This is only needed for
      # local runs, which are authenticated as a user. This is not needed for
      # GKE runs, which are authenticated as service account. (The service
      # account credentials are automatically picked up.)
      - ~/.config/gcloud:/root/.config/gcloud
networks:
  default:
    external:
      # This is only needed for indexing data into an Elasticsearch container
      # from the data-explorer repo. Use the network from that repo.
      name: dataexplorer_default
